apiVersion: v1
kind: Pod
metadata:
  name: test-privileged-pod
  namespace: default
  labels:
    app: test
spec:
  containers:
    - name: nginx
      image: nginx:latest
      securityContext:
        privileged: true
